workflows:
  build-android:
    name: Build Android APK Only
    max_build_duration: 10
    environment:
      flutter: stable
      xcode: false
    scripts:
      - name: Prepare Flutter
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
